name: Release VigeoUnity library

#on:
#  push:
#    branches:
#      - master

# Manual release trigger
on: workflow_dispatch

env:
  LIBRARY_ROOT: Assets/Plugins/Vigeo

jobs:
  upm-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: quabug/create-upm-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # release version will be retrieved from [dev.vigeo.core] package (assuming version is synced between packages)
        upm_package_path: ${{env.LIBRARY_ROOT}}/dev.vigeo.core
        upm_tag_prefix: v
